{
 "title": "OdahuFlow Operator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(gin_requests_total, namespace)"
   },
   { "name": "Quantile", "query": "0.99, 0.95, 0.90, 0.75, 0.5" }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(up{job=~\".*operator\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\".*-operator\",namespace=\"$namespace\"}",
     "legendFormat": "Pod name = {{pod}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=~\".*operator.*\",container=\"operator\"})",
       "legendFormat": "Requests of memory: pod name = {{pod}}"
      },
      {
       "expr": "sum by(pod) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=~\".*operator.*\",container=\"operator\"})",
       "legendFormat": "Limit of memory: pod name = {{pod}}"
      },
      {
       "expr": "sum by(pod) (container_memory_usage_bytes{namespace=\"$namespace\",pod=~\".*operator.*\",container=\"operator\"})",
       "legendFormat": "Usage of memory: pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=~\".*operator.*\",container=\"operator\"})",
       "legendFormat": "Requests of cpu: pod name = {{pod}}"
      },
      {
       "expr": "sum by(pod) (kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=~\".*operator.*\",container=\"operator\"})",
       "legendFormat": "Limit of cpu: pod name = {{pod}}"
      },
      {
       "expr": "sum by(pod) (rate(process_cpu_seconds_total{namespace=\"$namespace\",pod=~\".*operator.*\"}[5m]))",
       "legendFormat": "Usage of cpu: pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\".*operator.*\"}[5m]))",
       "legendFormat": "Recieve: pod name = {{pod}}"
      },
      {
       "expr": "sum by(pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=~\".*operator.*\"}[5m]))",
       "legendFormat": "Transmit: pod name = {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconcile latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($Quantile, rate(controller_runtime_reconcile_time_seconds_bucket{namespace=\"$namespace\",pod=~\".*operator.*\"}[5m]))",
       "legendFormat": "Pod name = {{pod}} , Controller = {{controller}}"
      }
     ]
    },
    {
     "title": "Current Queue size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "workqueue_depth{namespace=\"$namespace\",pod=~\".*operator.*\"}",
       "legendFormat": "Pod name = {{pod}}, name = {{name}}"
      }
     ]
    },
    {
     "title": "Queue growing",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(workqueue_adds_total{namespace=\"$namespace\",pod=~\".*operator.*\"}[5m])",
       "legendFormat": "Pod name = {{pod}}, name = {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency of GET requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(histogram_quantile($Quantile, rate(rest_client_request_latency_seconds_bucket{namespace=\"$namespace\",pod=~\".*operator.*\",verb=\"GET\"}[5m]))) by (pod)",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Latency of POST requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(histogram_quantile($Quantile, rate(rest_client_request_latency_seconds_bucket{namespace=\"$namespace\",pod=~\".*operator.*\",verb=\"POST\"}[5m]))) by (pod)",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Latency of DELETE requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(histogram_quantile($Quantile, rate(rest_client_request_latency_seconds_bucket{namespace=\"$namespace\",pod=~\".*operator.*\",verb=\"DELETE\"}[5m]))) by (pod)",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Latency of UPDATE requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($Quantile, rate(rest_client_request_latency_seconds_bucket{namespace=\"$namespace\",pod=~\".*operator.*\",verb=\"PUT\"}[5m]))",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{namespace=\"$namespace\",pod=~\".*operator.*\"}[5m]) / rate(go_gc_duration_seconds_count{namespace=\"$namespace\",pod=~\".*operator.*\"}[5m])",
       "legendFormat": "Next GC: pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Next GC",
     "type": "graph",
     "description": "Number of heap bytes when next garbage collection will take place",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_next_gc_bytes{namespace=\"$namespace\",pod=~\".*operator.*\"}",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    },
    {
     "title": "Stack size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_sys_bytes{namespace=\"$namespace\",pod=~\".*operator.*\"}\n",
       "legendFormat": "Pod name = {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}