{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-api"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "api" "root" .) | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "odahuflow.helm-labels-for-search" (dict "component" "api" "root" .) | nindent 6 }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        {{- include "odahuflow.helm-labels" (dict "component" "api" "root" .) | nindent 8 }}
        odahu-flow-authorization: enabled
    spec:
      {{- if .Values.rbac}}
      serviceAccountName: "{{ .Release.Name }}-api"
      {{- end}}
      volumes:
        - name: config
          secret:
            secretName: "{{ .Release.Name }}-api-config"
{{- if .Values.api.volumes }}
{{ toYaml .Values.api.volumes | indent 8 }}
{{- end }}
      containers:
      - name: api
        image: "{{ include "odahuflow.image-name" (dict "root" . "service" .Values.api "tpl" "%sodahu-flow-api:%s") }}"
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
        volumeMounts:
          - name: config
            mountPath: "/etc/odahu-flow"
            readOnly: true
{{- if .Values.api.volumeMounts }}
{{ toYaml .Values.api.volumeMounts | indent 10 }}
{{- end }}
        {{- if .Values.api.env }}
        env:
          {{- range $key, $value := .Values.api.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        command:
          - ./api
        args:
          - --config
          - /etc/odahu-flow/config.yaml
        ports:
          - containerPort: 5000
            name: api
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 120
          timeoutSeconds: 8
          failureThreshold: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-api"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "api" "root" .) | nindent 4 }}
spec:
  selector:
    {{- include "odahuflow.helm-labels-for-search" (dict "component" "api" "root" .) | nindent 4 }}
  ports:
  - name: http
    targetPort: 5000
    port: {{ .Values.api.port }}
    protocol: TCP
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-api-config"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "api" "root" .) | nindent 4 }}
data:
  "config.yaml": |
    {{ toYaml .Values.config | b64enc }}
