coverage:
  range: "80...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  branches:               # branch names that can post comment
    - "master"
    - "develop"
