---
# TODO: Remove after implementation of the issue https://github.com/legion-platform/legion/issues/1008
apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Release.Name }}-training-config"
    namespace: "{{ .Values.config.training.namespace }}"
    labels:
        {{- include "odahuflow.helm-labels" (dict "component" "api" "root" .) | nindent 4 }}
data:
    "config.yaml": |
        {{ toYaml .Values.config | b64enc }}
---
# TODO: Remove after implementation of the issue https://github.com/legion-platform/legion/issues/1008
apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Release.Name }}-packaging-config"
    namespace: "{{ .Values.config.packaging.namespace }}"
    labels:
        {{- include "odahuflow.helm-labels" (dict "component" "api" "root" .) | nindent 4 }}
data:
    "config.yaml": |
        {{ toYaml .Values.config | b64enc }}
