// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	batch "github.com/odahu/odahu-flow/packages/operator/pkg/apis/batch"

	mock "github.com/stretchr/testify/mock"
)

// BatchInferenceServiceAPI is an autogenerated mock type for the BatchInferenceServiceAPI type
type BatchInferenceServiceAPI struct {
	mock.Mock
}

// Get provides a mock function with given fields: ID
func (_m *BatchInferenceServiceAPI) Get(ID string) (batch.InferenceService, error) {
	ret := _m.Called(ID)

	var r0 batch.InferenceService
	if rf, ok := ret.Get(0).(func(string) batch.InferenceService); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(batch.InferenceService)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportJobRun provides a mock function with given fields: ID, RunInfo
func (_m *BatchInferenceServiceAPI) ReportJobRun(ID string, RunInfo batch.InferenceJobRun) error {
	ret := _m.Called(ID, RunInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, batch.InferenceJobRun) error); ok {
		r0 = rf(ID, RunInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
