// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	connection "github.com/odahu/odahu-flow/packages/operator/pkg/apis/connection"

	mock "github.com/stretchr/testify/mock"
)

// ConnGetter is an autogenerated mock type for the ConnGetter type
type ConnGetter struct {
	mock.Mock
}

// GetConnection provides a mock function with given fields: id
func (_m *ConnGetter) GetConnection(id string) (*connection.Connection, error) {
	ret := _m.Called(id)

	var r0 *connection.Connection
	if rf, ok := ret.Get(0).(func(string) *connection.Connection); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*connection.Connection)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
