// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	filter "github.com/odahu/odahu-flow/packages/operator/pkg/utils/filter"
	mock "github.com/stretchr/testify/mock"

	packaging "github.com/odahu/odahu-flow/packages/operator/pkg/apis/packaging"
)

// PackagingIntegrationRepository is an autogenerated mock type for the PackagingIntegrationRepository type
type PackagingIntegrationRepository struct {
	mock.Mock
}

// CreatePackagingIntegration provides a mock function with given fields: md
func (_m *PackagingIntegrationRepository) CreatePackagingIntegration(md *packaging.PackagingIntegration) error {
	ret := _m.Called(md)

	var r0 error
	if rf, ok := ret.Get(0).(func(*packaging.PackagingIntegration) error); ok {
		r0 = rf(md)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePackagingIntegration provides a mock function with given fields: id
func (_m *PackagingIntegrationRepository) DeletePackagingIntegration(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPackagingIntegration provides a mock function with given fields: id
func (_m *PackagingIntegrationRepository) GetPackagingIntegration(id string) (*packaging.PackagingIntegration, error) {
	ret := _m.Called(id)

	var r0 *packaging.PackagingIntegration
	if rf, ok := ret.Get(0).(func(string) *packaging.PackagingIntegration); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*packaging.PackagingIntegration)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPackagingIntegrationList provides a mock function with given fields: options
func (_m *PackagingIntegrationRepository) GetPackagingIntegrationList(options ...filter.ListOption) ([]packaging.PackagingIntegration, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []packaging.PackagingIntegration
	if rf, ok := ret.Get(0).(func(...filter.ListOption) []packaging.PackagingIntegration); ok {
		r0 = rf(options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]packaging.PackagingIntegration)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...filter.ListOption) error); ok {
		r1 = rf(options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePackagingIntegration provides a mock function with given fields: md
func (_m *PackagingIntegrationRepository) UpdatePackagingIntegration(md *packaging.PackagingIntegration) error {
	ret := _m.Called(md)

	var r0 error
	if rf, ok := ret.Get(0).(func(*packaging.PackagingIntegration) error); ok {
		r0 = rf(md)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
