// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"
	"github.com/odahu/odahu-flow/packages/operator/pkg/apis/event"

	mock "github.com/stretchr/testify/mock"
)

// ModelDeploymentEventGetter is an autogenerated mock type for the ModelDeploymentEventGetter type
type ModelDeploymentEventGetter struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, cursor
func (_m *ModelDeploymentEventGetter) Get(ctx context.Context, cursor int) ([]event.DeploymentEvent, int, error) {
	ret := _m.Called(ctx, cursor)

	var r0 []event.DeploymentEvent
	if rf, ok := ret.Get(0).(func(context.Context, int) []event.DeploymentEvent); ok {
		r0 = rf(ctx, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]event.DeploymentEvent)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, int) int); ok {
		r1 = rf(ctx, cursor)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, cursor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
