// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	model_route "github.com/odahu/odahu-flow/packages/operator/pkg/repository/outbox/model_route"
	mock "github.com/stretchr/testify/mock"
)

// RoutesEventReader is an autogenerated mock type for the RoutesEventReader type
type RoutesEventReader struct {
	mock.Mock
}

// Get provides a mock function with given fields: cursor
func (_m *RoutesEventReader) Get(cursor int) ([]model_route.RouteEvent, int, error) {
	ret := _m.Called(cursor)

	var r0 []model_route.RouteEvent
	if rf, ok := ret.Get(0).(func(int) []model_route.RouteEvent); ok {
		r0 = rf(cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model_route.RouteEvent)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(int) int); ok {
		r1 = rf(cursor)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(int) error); ok {
		r2 = rf(cursor)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
