// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	apisdeployment "github.com/odahu/odahu-flow/packages/operator/pkg/apis/deployment"

	filter "github.com/odahu/odahu-flow/packages/operator/pkg/utils/filter"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	v1alpha1 "github.com/odahu/odahu-flow/packages/operator/api/v1alpha1"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields: ctx
func (_m *Repository) BeginTransaction(ctx context.Context) (*sql.Tx, error) {
	ret := _m.Called(ctx)

	var r0 *sql.Tx
	if rf, ok := ret.Get(0).(func(context.Context) *sql.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateModelDeployment provides a mock function with given fields: ctx, tx, md
func (_m *Repository) CreateModelDeployment(ctx context.Context, tx *sql.Tx, md *apisdeployment.ModelDeployment) error {
	ret := _m.Called(ctx, tx, md)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, *apisdeployment.ModelDeployment) error); ok {
		r0 = rf(ctx, tx, md)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteModelDeployment provides a mock function with given fields: ctx, tx, id
func (_m *Repository) DeleteModelDeployment(ctx context.Context, tx *sql.Tx, id string) error {
	ret := _m.Called(ctx, tx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string) error); ok {
		r0 = rf(ctx, tx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetModelDeployment provides a mock function with given fields: ctx, tx, id
func (_m *Repository) GetModelDeployment(ctx context.Context, tx *sql.Tx, id string) (*apisdeployment.ModelDeployment, error) {
	ret := _m.Called(ctx, tx, id)

	var r0 *apisdeployment.ModelDeployment
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string) *apisdeployment.ModelDeployment); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apisdeployment.ModelDeployment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, string) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetModelDeploymentList provides a mock function with given fields: ctx, tx, options
func (_m *Repository) GetModelDeploymentList(ctx context.Context, tx *sql.Tx, options ...filter.ListOption) ([]apisdeployment.ModelDeployment, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, tx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []apisdeployment.ModelDeployment
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, ...filter.ListOption) []apisdeployment.ModelDeployment); ok {
		r0 = rf(ctx, tx, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]apisdeployment.ModelDeployment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *sql.Tx, ...filter.ListOption) error); ok {
		r1 = rf(ctx, tx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetDeletionMark provides a mock function with given fields: ctx, tx, id, value
func (_m *Repository) SetDeletionMark(ctx context.Context, tx *sql.Tx, id string, value bool) error {
	ret := _m.Called(ctx, tx, id, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, bool) error); ok {
		r0 = rf(ctx, tx, id, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateModelDeployment provides a mock function with given fields: ctx, tx, md
func (_m *Repository) UpdateModelDeployment(ctx context.Context, tx *sql.Tx, md *apisdeployment.ModelDeployment) error {
	ret := _m.Called(ctx, tx, md)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, *apisdeployment.ModelDeployment) error); ok {
		r0 = rf(ctx, tx, md)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateModelDeploymentStatus provides a mock function with given fields: ctx, tx, id, s
func (_m *Repository) UpdateModelDeploymentStatus(ctx context.Context, tx *sql.Tx, id string, s v1alpha1.ModelDeploymentStatus) error {
	ret := _m.Called(ctx, tx, id, s)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.Tx, string, v1alpha1.ModelDeploymentStatus) error); ok {
		r0 = rf(ctx, tx, id, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
