// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	context "context"

	filter "github.com/odahu/odahu-flow/packages/operator/pkg/utils/filter"
	mock "github.com/stretchr/testify/mock"

	training "github.com/odahu/odahu-flow/packages/operator/pkg/apis/training"

	v1alpha1 "github.com/odahu/odahu-flow/packages/operator/api/v1alpha1"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateModelTraining provides a mock function with given fields: ctx, qrr, mt
func (_m *Repository) CreateModelTraining(ctx context.Context, mt *training.ModelTraining) error {
	ret := _m.Called(ctx, mt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *training.ModelTraining) error); ok {
		r0 = rf(ctx, mt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteModelTraining provides a mock function with given fields: ctx, id
func (_m *Repository) DeleteModelTraining(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetModelTraining provides a mock function with given fields: ctx, id
func (_m *Repository) GetModelTraining(ctx context.Context, id string) (*training.ModelTraining, error) {
	ret := _m.Called(ctx, id)

	var r0 *training.ModelTraining
	if rf, ok := ret.Get(0).(func(context.Context, string) *training.ModelTraining); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*training.ModelTraining)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetModelTrainingList provides a mock function with given fields: ctx, options
func (_m *Repository) GetModelTrainingList(ctx context.Context, options ...filter.ListOption) ([]training.ModelTraining, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []training.ModelTraining
	if rf, ok := ret.Get(0).(func(context.Context, ...filter.ListOption) []training.ModelTraining); ok {
		r0 = rf(ctx, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]training.ModelTraining)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...filter.ListOption) error); ok {
		r1 = rf(ctx, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetDeletionMark provides a mock function with given fields: ctx, id, value
func (_m *Repository) SetDeletionMark(ctx context.Context, id string, value bool) error {
	ret := _m.Called(ctx, id, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateModelTraining provides a mock function with given fields: ctx, mt
func (_m *Repository) UpdateModelTraining(ctx context.Context, mt *training.ModelTraining) error {
	ret := _m.Called(ctx, mt)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *training.ModelTraining) error); ok {
		r0 = rf(ctx, mt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateModelTrainingStatus provides a mock function with given fields: ctx, id, s
func (_m *Repository) UpdateModelTrainingStatus(ctx context.Context, id string, s v1alpha1.ModelTrainingStatus) error {
	ret := _m.Called(ctx, id, s)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1alpha1.ModelTrainingStatus) error); ok {
		r0 = rf(ctx, id, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

func (_m *Repository) BeginTransaction(ctx context.Context) error {
	panic("implement me")
}

func (_m *Repository) Commit() error {
	panic("implement me")
}

func (_m *Repository) Rollback() error {
	panic("implement me")
}
