{{ if .Values.config.deployment.enabled }}
{{ if .Values.feedback.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: "{{ .Release.Name }}-feedback"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "feedback-collector" "root" .) | nindent 4 }}
  namespace: istio-system
spec:
  workloadLabels:
    app: istio-ingressgateway
  filters:
    - listenerMatch:
        portNumber: 80
        listenerType: GATEWAY
        listenerProtocol: HTTP
      filterName: envoy.filters.http.tap
      filterType: HTTP
      filterConfig:
        common_config:
          admin_config:
            config_id: feedback
{{- end }}
{{- end }}
