{{ if .Values.config.deployment.enabled }}
{{ if .Values.feedback.enabled -}}
{{ if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-collector"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "feedback-collector" "root" .) | nindent 4 }}
    {{- range $key, $value := .Values.metrics.serviceMonitoringLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: api
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "odahuflow.helm-labels-for-search" (dict "component" "feedback-collector" "root" .) | nindent 6 }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-rq-catcher"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "feedback-rq-catcher" "root" .) | nindent 4 }}
    {{- range $key, $value := .Values.metrics.serviceMonitoringLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: monitoring
  namespaceSelector:
    matchNames:
    - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "odahuflow.helm-labels-for-search" (dict "component" "feedback-rq-catcher" "root" .) | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}