# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models import util


class APILocalBackendConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, local_backend_crd_path: str=None):  # noqa: E501
        """APILocalBackendConfig - a model defined in Swagger

        :param local_backend_crd_path: The local_backend_crd_path of this APILocalBackendConfig.  # noqa: E501
        :type local_backend_crd_path: str
        """
        self.swagger_types = {
            'local_backend_crd_path': str
        }

        self.attribute_map = {
            'local_backend_crd_path': 'localBackendCrdPath'
        }

        self._local_backend_crd_path = local_backend_crd_path

    @classmethod
    def from_dict(cls, dikt) -> 'APILocalBackendConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The APILocalBackendConfig of this APILocalBackendConfig.  # noqa: E501
        :rtype: APILocalBackendConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def local_backend_crd_path(self) -> str:
        """Gets the local_backend_crd_path of this APILocalBackendConfig.

        Path to a dir with ODAHU CRDs  # noqa: E501

        :return: The local_backend_crd_path of this APILocalBackendConfig.
        :rtype: str
        """
        return self._local_backend_crd_path

    @local_backend_crd_path.setter
    def local_backend_crd_path(self, local_backend_crd_path: str):
        """Sets the local_backend_crd_path of this APILocalBackendConfig.

        Path to a dir with ODAHU CRDs  # noqa: E501

        :param local_backend_crd_path: The local_backend_crd_path of this APILocalBackendConfig.
        :type local_backend_crd_path: str
        """

        self._local_backend_crd_path = local_backend_crd_path
