# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models import util


class FeedbackModelFeedback(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, model_name: str=None, model_version: str=None, payload: object=None, request_id: str=None):  # noqa: E501
        """FeedbackModelFeedback - a model defined in Swagger

        :param model_name: The model_name of this FeedbackModelFeedback.  # noqa: E501
        :type model_name: str
        :param model_version: The model_version of this FeedbackModelFeedback.  # noqa: E501
        :type model_version: str
        :param payload: The payload of this FeedbackModelFeedback.  # noqa: E501
        :type payload: object
        :param request_id: The request_id of this FeedbackModelFeedback.  # noqa: E501
        :type request_id: str
        """
        self.swagger_types = {
            'model_name': str,
            'model_version': str,
            'payload': object,
            'request_id': str
        }

        self.attribute_map = {
            'model_name': 'modelName',
            'model_version': 'modelVersion',
            'payload': 'payload',
            'request_id': 'requestID'
        }

        self._model_name = model_name
        self._model_version = model_version
        self._payload = payload
        self._request_id = request_id

    @classmethod
    def from_dict(cls, dikt) -> 'FeedbackModelFeedback':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The feedback.ModelFeedback of this FeedbackModelFeedback.  # noqa: E501
        :rtype: FeedbackModelFeedback
        """
        return util.deserialize_model(dikt, cls)

    @property
    def model_name(self) -> str:
        """Gets the model_name of this FeedbackModelFeedback.


        :return: The model_name of this FeedbackModelFeedback.
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name: str):
        """Sets the model_name of this FeedbackModelFeedback.


        :param model_name: The model_name of this FeedbackModelFeedback.
        :type model_name: str
        """

        self._model_name = model_name

    @property
    def model_version(self) -> str:
        """Gets the model_version of this FeedbackModelFeedback.


        :return: The model_version of this FeedbackModelFeedback.
        :rtype: str
        """
        return self._model_version

    @model_version.setter
    def model_version(self, model_version: str):
        """Sets the model_version of this FeedbackModelFeedback.


        :param model_version: The model_version of this FeedbackModelFeedback.
        :type model_version: str
        """

        self._model_version = model_version

    @property
    def payload(self) -> object:
        """Gets the payload of this FeedbackModelFeedback.


        :return: The payload of this FeedbackModelFeedback.
        :rtype: object
        """
        return self._payload

    @payload.setter
    def payload(self, payload: object):
        """Sets the payload of this FeedbackModelFeedback.


        :param payload: The payload of this FeedbackModelFeedback.
        :type payload: object
        """

        self._payload = payload

    @property
    def request_id(self) -> str:
        """Gets the request_id of this FeedbackModelFeedback.


        :return: The request_id of this FeedbackModelFeedback.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this FeedbackModelFeedback.


        :param request_id: The request_id of this FeedbackModelFeedback.
        :type request_id: str
        """

        self._request_id = request_id
