# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models.predictor_webhook_trigger import PredictorWebhookTrigger  # noqa: F401,E501
from odahuflow.sdk.models import util


class InferenceServiceTriggers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, webhook: PredictorWebhookTrigger=None):  # noqa: E501
        """InferenceServiceTriggers - a model defined in Swagger

        :param webhook: The webhook of this InferenceServiceTriggers.  # noqa: E501
        :type webhook: PredictorWebhookTrigger
        """
        self.swagger_types = {
            'webhook': PredictorWebhookTrigger
        }

        self.attribute_map = {
            'webhook': 'webhook'
        }

        self._webhook = webhook

    @classmethod
    def from_dict(cls, dikt) -> 'InferenceServiceTriggers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The InferenceServiceTriggers of this InferenceServiceTriggers.  # noqa: E501
        :rtype: InferenceServiceTriggers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def webhook(self) -> PredictorWebhookTrigger:
        """Gets the webhook of this InferenceServiceTriggers.

        Webhook provides a REST API to execute InferenceJob that correspond to this service  # noqa: E501

        :return: The webhook of this InferenceServiceTriggers.
        :rtype: PredictorWebhookTrigger
        """
        return self._webhook

    @webhook.setter
    def webhook(self, webhook: PredictorWebhookTrigger):
        """Sets the webhook of this InferenceServiceTriggers.

        Webhook provides a REST API to execute InferenceJob that correspond to this service  # noqa: E501

        :param webhook: The webhook of this InferenceServiceTriggers.
        :type webhook: PredictorWebhookTrigger
        """

        self._webhook = webhook
