# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models.model_meta import ModelMeta  # noqa: F401,E501
from odahuflow.sdk.models import util


class LocalModelSource(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, meta: ModelMeta=None, model_path: str=None):  # noqa: E501
        """LocalModelSource - a model defined in Swagger

        :param meta: The meta of this LocalModelSource.  # noqa: E501
        :type meta: ModelMeta
        :param model_path: The model_path of this LocalModelSource.  # noqa: E501
        :type model_path: str
        """
        self.swagger_types = {
            'meta': ModelMeta,
            'model_path': str
        }

        self.attribute_map = {
            'meta': 'meta',
            'model_path': 'modelPath'
        }

        self._meta = meta
        self._model_path = model_path

    @classmethod
    def from_dict(cls, dikt) -> 'LocalModelSource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LocalModelSource of this LocalModelSource.  # noqa: E501
        :rtype: LocalModelSource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def meta(self) -> ModelMeta:
        """Gets the meta of this LocalModelSource.


        :return: The meta of this LocalModelSource.
        :rtype: ModelMeta
        """
        return self._meta

    @meta.setter
    def meta(self, meta: ModelMeta):
        """Sets the meta of this LocalModelSource.


        :param meta: The meta of this LocalModelSource.
        :type meta: ModelMeta
        """

        self._meta = meta

    @property
    def model_path(self) -> str:
        """Gets the model_path of this LocalModelSource.

        ModelPath is a directory inside container where ML model files are located  # noqa: E501

        :return: The model_path of this LocalModelSource.
        :rtype: str
        """
        return self._model_path

    @model_path.setter
    def model_path(self, model_path: str):
        """Sets the model_path of this LocalModelSource.

        ModelPath is a directory inside container where ML model files are located  # noqa: E501

        :param model_path: The model_path of this LocalModelSource.
        :type model_path: str
        """

        self._model_path = model_path
