# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models.outbox_deployment_event import OutboxDeploymentEvent  # noqa: F401,E501
from odahuflow.sdk.models import util


class ModelDeploymentEventsResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cursor: int=None, events: List[OutboxDeploymentEvent]=None):  # noqa: E501
        """ModelDeploymentEventsResponse - a model defined in Swagger

        :param cursor: The cursor of this ModelDeploymentEventsResponse.  # noqa: E501
        :type cursor: int
        :param events: The events of this ModelDeploymentEventsResponse.  # noqa: E501
        :type events: List[OutboxDeploymentEvent]
        """
        self.swagger_types = {
            'cursor': int,
            'events': List[OutboxDeploymentEvent]
        }

        self.attribute_map = {
            'cursor': 'cursor',
            'events': 'events'
        }

        self._cursor = cursor
        self._events = events

    @classmethod
    def from_dict(cls, dikt) -> 'ModelDeploymentEventsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModelDeploymentEventsResponse of this ModelDeploymentEventsResponse.  # noqa: E501
        :rtype: ModelDeploymentEventsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cursor(self) -> int:
        """Gets the cursor of this ModelDeploymentEventsResponse.


        :return: The cursor of this ModelDeploymentEventsResponse.
        :rtype: int
        """
        return self._cursor

    @cursor.setter
    def cursor(self, cursor: int):
        """Sets the cursor of this ModelDeploymentEventsResponse.


        :param cursor: The cursor of this ModelDeploymentEventsResponse.
        :type cursor: int
        """

        self._cursor = cursor

    @property
    def events(self) -> List[OutboxDeploymentEvent]:
        """Gets the events of this ModelDeploymentEventsResponse.


        :return: The events of this ModelDeploymentEventsResponse.
        :rtype: List[OutboxDeploymentEvent]
        """
        return self._events

    @events.setter
    def events(self, events: List[OutboxDeploymentEvent]):
        """Sets the events of this ModelDeploymentEventsResponse.


        :param events: The events of this ModelDeploymentEventsResponse.
        :type events: List[OutboxDeploymentEvent]
        """

        self._events = events
