# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models import util


class NodePool(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, node_selector: Dict[str, str]=None, tags: List[str]=None):  # noqa: E501
        """NodePool - a model defined in Swagger

        :param node_selector: The node_selector of this NodePool.  # noqa: E501
        :type node_selector: Dict[str, str]
        :param tags: The tags of this NodePool.  # noqa: E501
        :type tags: List[str]
        """
        self.swagger_types = {
            'node_selector': Dict[str, str],
            'tags': List[str]
        }

        self.attribute_map = {
            'node_selector': 'nodeSelector',
            'tags': 'tags'
        }

        self._node_selector = node_selector
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'NodePool':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NodePool of this NodePool.  # noqa: E501
        :rtype: NodePool
        """
        return util.deserialize_model(dikt, cls)

    @property
    def node_selector(self) -> Dict[str, str]:
        """Gets the node_selector of this NodePool.


        :return: The node_selector of this NodePool.
        :rtype: Dict[str, str]
        """
        return self._node_selector

    @node_selector.setter
    def node_selector(self, node_selector: Dict[str, str]):
        """Sets the node_selector of this NodePool.


        :param node_selector: The node_selector of this NodePool.
        :type node_selector: Dict[str, str]
        """

        self._node_selector = node_selector

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this NodePool.


        :return: The tags of this NodePool.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this NodePool.


        :param tags: The tags of this NodePool.
        :type tags: List[str]
        """

        self._tags = tags
