# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models import util


class ObjectStorage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, conn_name: str=None, path: str=None):  # noqa: E501
        """ObjectStorage - a model defined in Swagger

        :param conn_name: The conn_name of this ObjectStorage.  # noqa: E501
        :type conn_name: str
        :param path: The path of this ObjectStorage.  # noqa: E501
        :type path: str
        """
        self.swagger_types = {
            'conn_name': str,
            'path': str
        }

        self.attribute_map = {
            'conn_name': 'connName',
            'path': 'path'
        }

        self._conn_name = conn_name
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'ObjectStorage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ObjectStorage of this ObjectStorage.  # noqa: E501
        :rtype: ObjectStorage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def conn_name(self) -> str:
        """Gets the conn_name of this ObjectStorage.


        :return: The conn_name of this ObjectStorage.
        :rtype: str
        """
        return self._conn_name

    @conn_name.setter
    def conn_name(self, conn_name: str):
        """Sets the conn_name of this ObjectStorage.


        :param conn_name: The conn_name of this ObjectStorage.
        :type conn_name: str
        """

        self._conn_name = conn_name

    @property
    def path(self) -> str:
        """Gets the path of this ObjectStorage.


        :return: The path of this ObjectStorage.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path: str):
        """Sets the path of this ObjectStorage.


        :param path: The path of this ObjectStorage.
        :type path: str
        """

        self._path = path
