# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models.training_integration_spec import TrainingIntegrationSpec  # noqa: F401,E501
from odahuflow.sdk.models.training_integration_status import TrainingIntegrationStatus  # noqa: F401,E501
from odahuflow.sdk.models import util


class TrainingIntegration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, created_at: str=None, id: str=None, spec: TrainingIntegrationSpec=None, status: TrainingIntegrationStatus=None, updated_at: str=None):  # noqa: E501
        """TrainingIntegration - a model defined in Swagger

        :param created_at: The created_at of this TrainingIntegration.  # noqa: E501
        :type created_at: str
        :param id: The id of this TrainingIntegration.  # noqa: E501
        :type id: str
        :param spec: The spec of this TrainingIntegration.  # noqa: E501
        :type spec: TrainingIntegrationSpec
        :param status: The status of this TrainingIntegration.  # noqa: E501
        :type status: TrainingIntegrationStatus
        :param updated_at: The updated_at of this TrainingIntegration.  # noqa: E501
        :type updated_at: str
        """
        self.swagger_types = {
            'created_at': str,
            'id': str,
            'spec': TrainingIntegrationSpec,
            'status': TrainingIntegrationStatus,
            'updated_at': str
        }

        self.attribute_map = {
            'created_at': 'createdAt',
            'id': 'id',
            'spec': 'spec',
            'status': 'status',
            'updated_at': 'updatedAt'
        }

        self._created_at = created_at
        self._id = id
        self._spec = spec
        self._status = status
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'TrainingIntegration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TrainingIntegration of this TrainingIntegration.  # noqa: E501
        :rtype: TrainingIntegration
        """
        return util.deserialize_model(dikt, cls)

    @property
    def created_at(self) -> str:
        """Gets the created_at of this TrainingIntegration.

        CreatedAt  # noqa: E501

        :return: The created_at of this TrainingIntegration.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this TrainingIntegration.

        CreatedAt  # noqa: E501

        :param created_at: The created_at of this TrainingIntegration.
        :type created_at: str
        """

        self._created_at = created_at

    @property
    def id(self) -> str:
        """Gets the id of this TrainingIntegration.

        Training integration id  # noqa: E501

        :return: The id of this TrainingIntegration.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this TrainingIntegration.

        Training integration id  # noqa: E501

        :param id: The id of this TrainingIntegration.
        :type id: str
        """

        self._id = id

    @property
    def spec(self) -> TrainingIntegrationSpec:
        """Gets the spec of this TrainingIntegration.

        Training integration specification  # noqa: E501

        :return: The spec of this TrainingIntegration.
        :rtype: TrainingIntegrationSpec
        """
        return self._spec

    @spec.setter
    def spec(self, spec: TrainingIntegrationSpec):
        """Sets the spec of this TrainingIntegration.

        Training integration specification  # noqa: E501

        :param spec: The spec of this TrainingIntegration.
        :type spec: TrainingIntegrationSpec
        """

        self._spec = spec

    @property
    def status(self) -> TrainingIntegrationStatus:
        """Gets the status of this TrainingIntegration.

        Training integration status  # noqa: E501

        :return: The status of this TrainingIntegration.
        :rtype: TrainingIntegrationStatus
        """
        return self._status

    @status.setter
    def status(self, status: TrainingIntegrationStatus):
        """Sets the status of this TrainingIntegration.

        Training integration status  # noqa: E501

        :param status: The status of this TrainingIntegration.
        :type status: TrainingIntegrationStatus
        """

        self._status = status

    @property
    def updated_at(self) -> str:
        """Gets the updated_at of this TrainingIntegration.

        UpdatedAt  # noqa: E501

        :return: The updated_at of this TrainingIntegration.
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: str):
        """Sets the updated_at of this TrainingIntegration.

        UpdatedAt  # noqa: E501

        :param updated_at: The updated_at of this TrainingIntegration.
        :type updated_at: str
        """

        self._updated_at = updated_at
