# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models.claims import Claims  # noqa: F401,E501
from odahuflow.sdk.models import util


class UserConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, claims: Claims=None, sign_out_url: str=None):  # noqa: E501
        """UserConfig - a model defined in Swagger

        :param claims: The claims of this UserConfig.  # noqa: E501
        :type claims: Claims
        :param sign_out_url: The sign_out_url of this UserConfig.  # noqa: E501
        :type sign_out_url: str
        """
        self.swagger_types = {
            'claims': Claims,
            'sign_out_url': str
        }

        self.attribute_map = {
            'claims': 'claims',
            'sign_out_url': 'signOutUrl'
        }

        self._claims = claims
        self._sign_out_url = sign_out_url

    @classmethod
    def from_dict(cls, dikt) -> 'UserConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserConfig of this UserConfig.  # noqa: E501
        :rtype: UserConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def claims(self) -> Claims:
        """Gets the claims of this UserConfig.


        :return: The claims of this UserConfig.
        :rtype: Claims
        """
        return self._claims

    @claims.setter
    def claims(self, claims: Claims):
        """Sets the claims of this UserConfig.


        :param claims: The claims of this UserConfig.
        :type claims: Claims
        """

        self._claims = claims

    @property
    def sign_out_url(self) -> str:
        """Gets the sign_out_url of this UserConfig.

        The sign out endpoint logs out the authenticated  # noqa: E501

        :return: The sign_out_url of this UserConfig.
        :rtype: str
        """
        return self._sign_out_url

    @sign_out_url.setter
    def sign_out_url(self, sign_out_url: str):
        """Sets the sign_out_url of this UserConfig.

        The sign out endpoint logs out the authenticated  # noqa: E501

        :param sign_out_url: The sign_out_url of this UserConfig.
        :type sign_out_url: str
        """

        self._sign_out_url = sign_out_url
