# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models import util


class VCS(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, connection: str=None, reference: str=None):  # noqa: E501
        """VCS - a model defined in Swagger

        :param connection: The connection of this VCS.  # noqa: E501
        :type connection: str
        :param reference: The reference of this VCS.  # noqa: E501
        :type reference: str
        """
        self.swagger_types = {
            'connection': str,
            'reference': str
        }

        self.attribute_map = {
            'connection': 'connection',
            'reference': 'reference'
        }

        self._connection = connection
        self._reference = reference

    @classmethod
    def from_dict(cls, dikt) -> 'VCS':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VCS of this VCS.  # noqa: E501
        :rtype: VCS
        """
        return util.deserialize_model(dikt, cls)

    @property
    def connection(self) -> str:
        """Gets the connection of this VCS.

        Connection name for training model source  # noqa: E501

        :return: The connection of this VCS.
        :rtype: str
        """
        return self._connection

    @connection.setter
    def connection(self, connection: str):
        """Sets the connection of this VCS.

        Connection name for training model source  # noqa: E501

        :param connection: The connection of this VCS.
        :type connection: str
        """

        self._connection = connection

    @property
    def reference(self) -> str:
        """Gets the reference of this VCS.

        VCS Reference  # noqa: E501

        :return: The reference of this VCS.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this VCS.

        VCS Reference  # noqa: E501

        :param reference: The reference of this VCS.
        :type reference: str
        """

        self._reference = reference
