# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from odahuflow.sdk.models.base_model_ import Model
from odahuflow.sdk.models import util


class VCS(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, conn_name: str=None, reference: str=None):  # noqa: E501
        """VCS - a model defined in Swagger

        :param conn_name: The conn_name of this VCS.  # noqa: E501
        :type conn_name: str
        :param reference: The reference of this VCS.  # noqa: E501
        :type reference: str
        """
        self.swagger_types = {
            'conn_name': str,
            'reference': str
        }

        self.attribute_map = {
            'conn_name': 'connName',
            'reference': 'reference'
        }

        self._conn_name = conn_name
        self._reference = reference

    @classmethod
    def from_dict(cls, dikt) -> 'VCS':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VCS of this VCS.  # noqa: E501
        :rtype: VCS
        """
        return util.deserialize_model(dikt, cls)

    @property
    def conn_name(self) -> str:
        """Gets the conn_name of this VCS.


        :return: The conn_name of this VCS.
        :rtype: str
        """
        return self._conn_name

    @conn_name.setter
    def conn_name(self, conn_name: str):
        """Sets the conn_name of this VCS.


        :param conn_name: The conn_name of this VCS.
        :type conn_name: str
        """

        self._conn_name = conn_name

    @property
    def reference(self) -> str:
        """Gets the reference of this VCS.


        :return: The reference of this VCS.
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference: str):
        """Sets the reference of this VCS.


        :param reference: The reference of this VCS.
        :type reference: str
        """

        self._reference = reference
