import java.text.SimpleDateFormat

class Globals {
    static String rootCommit = null
    static String buildVersion = null
    static String dockerLabels = null
    static String dockerCacheArg = null
}

pipeline {
    agent { label 'ec2builder'}

    options{
        buildDiscarder(logRotator(numToKeepStr: '35', artifactNumToKeepStr: '35'))
    }
    environment {
        /*
        Job parameters
        */
        pathToCharts= "${WORKSPACE}/helms"
        sharedLibPath = "legion-cicd/pipelines/legionPipeline.groovy"
        //Git Branch to build package from
        param_git_branch = "${params.GitBranch}"

        /*
        Release parameters
        */
        //Set next releases version explicitly
        param_next_version = "${params.NextVersion}"
        //Release version to tag all artifacts to
        param_release_version = "${params.ReleaseVersion}"
        //Push release git tag
        param_push_git_tag = "${params.PushGitTag}"
        //Rewrite git tag i exists
        param_force_tag_push = "${params.ForceTagPush}"
        param_update_version_string = "${params.UpdateVersionString}"
        param_update_master = "${params.UpdateMaster}"
        //Build major version release and optionally push it to public repositories
        param_stable_release = "${params.StableRelease}"

        /*
        CICD repository
        */
        legionCicdGitlabKey = "${params.legionCicdGitlabKey}"
        param_git_deploy_key = "${params.GitDeployKey}"
        //Legion CICD repo url (for pipeline methods import)
        param_legion_cicd_repo = "${params.LegionCicdRepo}"
        //Legion repo branch (tag or branch name)
        param_legion_cicd_branch = "${params.LegionCicdBranch}"

        /*
        Helm
        */
        param_helm_repo_git_url = "${params.HelmRepoGitUrl}"
        param_helm_repo_git_branch = "${params.HelmRepoGitBranch}"
        param_helm_repository = "${params.HelmRepository}"

        /*
        Docker
        */
        param_dockerhub_publishing_enabled = "${params.DockerHubPublishingEnabled}"
        param_docker_registry = "${params.DockerRegistry}"
        param_docker_hub_registry = "${params.DockerHubRegistry}"
        param_enable_docker_cache = "${params.EnableDockerCache}"
        param_docker_cache_source = "${params.DockerCacheSource}"

        /*
        PyPi
        */
        param_pypi_public_url = "${params.PyPiPublicUrl}"
        param_pypi_public_creds = "pypi_public_cred"
        param_pypi_private_url = "${params.PyPiPrivateUrl}"
        param_pypi_private_creds = "nexus-local-repository"
        param_pypi_publishing_enabled = "${PyPiPublishingEnabled}"
    }

    stages {
        stage('Checkout and set build vars') {
            steps {
                cleanWs()
                checkout scm
                script {
                    sh 'echo RunningOn: $(curl http://checkip.amazonaws.com/)'

                    // import Legion components
                    sshagent(["${env.legionCicdGitlabKey}"]) {
                        print ("Checkout Legion-cicd repo")
                        sh"""#!/bin/bash -ex
                        mkdir -p \$(getent passwd \$(whoami) | cut -d: -f6)/.ssh && ssh-keyscan git.epam.com >> \$(getent passwd \$(whoami) | cut -d: -f6)/.ssh/known_hosts
                        if [ ! -d "legion-cicd" ]; then
                            git clone ${env.param_legion_cicd_repo} legion-cicd
                        fi
                        cd legion-cicd && git checkout ${env.param_legion_cicd_branch}
                        """

                        print ("Load odahuflow pipeline common library")
                        cicdLibrary = load "${env.sharedLibPath}"
                    }

                    verFiles = [
                            'packages/cli/odahuflow/cli/version.py',
                            'packages/sdk/odahuflow/sdk/version.py',
                            'packages/robot/odahuflow/robot/version.py',
                    ]
                    cicdLibrary.setBuildMeta(verFiles)
                }
            }
        }

        // Set Git Tag in case of stable release
        stage('Set GIT release Tag'){
            steps {
                script {
                    print (env.param_stable_release)
                    if (env.param_stable_release.toBoolean() && env.param_push_git_tag.toBoolean()){
                        cicdLibrary.setGitReleaseTag("${env.param_git_deploy_key}")
                    }
                    else {
                        print("Skipping release git tag push")
                    }
                }
            }
        }

        stage("Build Docker images & Run Tests") {
            parallel {
                stage('Build pipeline Docker agent') {
                    steps {
                        script {
                            cicdLibrary.buildLegionImage('odahu-flow-robot-tests', '.', 'containers/robot-tests/Dockerfile')
                            cicdLibrary.uploadDockerImage('odahu-flow-robot-tests', env.param_stable_release.toBoolean() && env.param_dockerhub_publishing_enabled.toBoolean())
                        }
                    }
                }
                stage("Build model trainer and operator images") {
                    steps {
                        script {
                            cicdLibrary.buildLegionImage('odahu-flow-operator-dependencies', ".", "containers/operator/Dockerfile", "--target builder")
                            cicdLibrary.buildLegionImage('odahu-flow-operator', ".", "containers/operator/Dockerfile", "--target operator --cache-from odahu/odahu-flow-operator-dependencies:${Globals.buildVersion}")
                            cicdLibrary.buildLegionImage('odahu-flow-api', ".", "containers/operator/Dockerfile", "--target api --cache-from odahu/odahu-flow-operator-dependencies:${Globals.buildVersion}")
                            cicdLibrary.buildLegionImage('odahu-flow-service-catalog', ".", "containers/operator/Dockerfile", "--target service-catalog --cache-from odahu/odahu-flow-operator-dependencies:${Globals.buildVersion}")
                            cicdLibrary.buildLegionImage('odahu-flow-model-trainer', ".", "containers/operator/Dockerfile", "--target model-trainer --cache-from odahu/odahu-flow-operator-dependencies:${Globals.buildVersion}")
                            cicdLibrary.buildLegionImage('odahu-flow-model-packager', ".", "containers/operator/Dockerfile", "--target model-packager --cache-from odahu/odahu-flow-operator-dependencies:${Globals.buildVersion}")
                        }
                    }
                }
                stage('Build odahuflowctl image') {
                    steps {
                        script {
                            cicdLibrary.buildLegionImage('odahu-flow-cli', '.', 'containers/odahu-flow-cli/Dockerfile')
                        }
                    }
                }
                stage("Build feedback images") {
                    steps {
                        script {
                            cicdLibrary.buildLegionImage('odahu-flow-feedback-dependencies', ".", "containers/feedback/Dockerfile", "--target builder")
                            cicdLibrary.buildLegionImage('odahu-flow-feedback-collector', ".", "containers/feedback/Dockerfile", "--target collector --cache-from odahu/odahu-flow-feedback-dependencies:${Globals.buildVersion}")
                            cicdLibrary.buildLegionImage('odahu-flow-feedback-rq-catcher', ".", "containers/feedback/Dockerfile", "--target rq-catcher --cache-from odahu/odahu-flow-feedback-dependencies:${Globals.buildVersion}")
                        }
                    }
                }
            }
        }

        stage('Upload artifacts'){
            parallel {
                stage("Upload PyPi Legion packages") {
                    steps {
                        script {
                            cicdLibrary.publishPythonPackage("packages/cli", env.param_pypi_private_creds, env.param_pypi_private_url, env.param_pypi_publishing_enabled, env.param_pypi_public_creds, env.param_pypi_public_url)
                            cicdLibrary.publishPythonPackage("packages/sdk", env.param_pypi_private_creds, env.param_pypi_private_url, env.param_pypi_publishing_enabled, env.param_pypi_public_creds, env.param_pypi_public_url)
                        }
                    }
                }
                stage('Package and upload helm charts'){
                    steps {
                        script {
                            cicdLibrary.uploadHelmCharts(env.pathToCharts)
                        }
                    }
                }
                stage("Upload model trainer image") {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-model-trainer', env.param_stable_release.toBoolean() && env.param_dockerhub_publishing_enabled.toBoolean())
                        }
                    }
                }
                stage("Upload odahuflowctl image") {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-cli', env.param_stable_release.toBoolean() && env.param_dockerhub_publishing_enabled.toBoolean())
                        }
                    }
                }
                stage("Upload model packager image") {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-model-packager', env.param_stable_release.toBoolean() && env.param_dockerhub_publishing_enabled.toBoolean())
                        }
                    }
                }
                stage("Upload model service catalog image") {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-service-catalog', env.param_stable_release.toBoolean() && env.param_dockerhub_publishing_enabled.toBoolean())
                        }
                    }
                }
                stage("Upload operator image") {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-operator', env.param_stable_release.toBoolean() && env.param_dockerhub_publishing_enabled.toBoolean())
                        }
                    }
                }
                stage("Upload feedback collector image") {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-feedback-collector', env.param_stable_release.toBoolean() && env.param_dockerhub_publishing_enabled.toBoolean())
                        }
                    }
                }
                stage("Upload feedback rq-catcher image") {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-feedback-rq-catcher', env.param_stable_release.toBoolean() && env.param_dockerhub_publishing_enabled.toBoolean())
                        }
                    }
                }
                stage('Upload Api Docker image') {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-api', env.param_stable_release.toBoolean() && env.param_dockerhub_publishing_enabled.toBoolean())
                        }
                    }
                }
                stage('Upload Operator dependencies') {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-operator-dependencies', false)
                        }
                    }
                }
                stage('Upload Feedback dependencies') {
                    steps {
                        script {
                            cicdLibrary.uploadDockerImage('odahu-flow-feedback-dependencies', false)
                        }
                    }
                }
            }
        }

        stage("Update Legion version string") {
            steps {
                script {
                    if (env.param_stable_release.toBoolean() && env.param_update_version_string.toBoolean()) {
                        cicdLibrary.updateVersionString(env.versionFile)
                    }
                    else {
                        print("Skipping version string update")
                    }
                }
            }
        }

        stage('Update Master branch'){
            steps {
                script {
                    if (env.param_update_master.toBoolean()){
                        cicdLibrary.updateMasterBranch()
                    }
                    else {
                        print("Skipping Master branch update")
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                print ("Load legion pipeline common library")
                legion = load "${env.sharedLibPath}"

                dir("${WORKSPACE}/legion-cicd") {
                    cicdLibrary.notifyBuild(currentBuild.currentResult)
                }
            }
            deleteDir()
        }
    }
}
