#!/bin/bash
set -e
set -o pipefail

PYLINT_FOLDER="target/pylint"
PYDOCSTYLE_FOLDER="target/pydocstyle"
VULTURE_WHITE_LIST="py_dead_code_whitelist.py"


function pylint_cmd() {
    package_dir="${1}"
    output_name="${2}"
    additional_pylint_args="${3}"

    pylint --output-format=parseable \
           ${additional_pylint_args} \
           --reports=no "packages/${package_dir}" 2>&1 | tee "${PYLINT_FOLDER}/odahu-flow-${output_name}.log" &
}

rm -rf "${PYLINT_FOLDER}"
mkdir -p "${PYLINT_FOLDER}"

# Ignoring models package because it contains autogenerated python code
pylint_cmd sdk/odahuflow sdk "--ignore models"
pylint_cmd cli/odahuflow cli
pylint_cmd robot/odahuflow robot

function pydocstyle_cmd() {
    package_dir="${1}"
    output_name="${2}"

    pydocstyle --ignore D301 \
               --match-dir '^(?!models).*' \
               --source "packages/${package_dir}" 2>&1 | tee "${PYDOCSTYLE_FOLDER}/odahu-flow-${output_name}.log" &
}

rm -rf "${PYDOCSTYLE_FOLDER}"
mkdir -p "${PYDOCSTYLE_FOLDER}"

# TODO: return or get rid of pydocstyle
# pydocstyle_cmd sdk/odahuflow sdk
# pydocstyle_cmd cli/odahuflow cli
# pydocstyle_cmd robot/odahuflow robot

# Run vulture dead code search against passed packages
# Ignore click commands (because it is interface of CLI package for end user) and autogenerated sdk models
function vulture_cmd() {
    packages_to_check="${@}"
    vulture ${packages_to_check} ${VULTURE_WHITE_LIST}  --exclude=models --ignore-decorators="@*.command"
}

# check SDK and CLI for dead code
vulture_cmd packages/sdk/odahuflow/sdk packages/cli/odahuflow/cli

FAIL=0
# Wait all background linters
for job in $(jobs -p)
do
    echo "${job}"
    echo "waiting..."
    wait "${job}" || ((FAIL = FAIL + 1))
done

cat ${PYLINT_FOLDER}/*.log > "${PYLINT_FOLDER}/odahuflow.log"

# TODO: return or get rid of pydocstyle
# cat ${PYDOCSTYLE_FOLDER}/*.log > "${PYDOCSTYLE_FOLDER}/odahuflow.log"

echo "You can find the result of linting here: ${PYLINT_FOLDER} and ${PYDOCSTYLE_FOLDER}"

if [[ "$FAIL" -ne "0" ]];
then
    echo "Failed $FAIL linters"
    exit 1
fi
