{{ if .Values.config.deployment.enabled }}
{{ if .Values.service_catalog.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}-service-catalog"
  namespace: "{{ .Values.config.deployment.namespace }}"
spec:
  hosts:
    - "*"
  gateways:
    - edge
  http:
    - match:
      - uri:
          exact: "{{ .Values.config.service_catalog.base_url }}"
      redirect:
        uri: {{ .Values.config.service_catalog.base_url }}/swagger/index.html
{{- end }}
{{- end }}
