apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
    controller-tools.k8s.io: "1.0"
  name: toolchainintegrations.odahuflow.odahu.org
spec:
  group: odahuflow.odahu.org
  names:
    kind: ToolchainIntegration
    plural: toolchainintegrations
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalEnvironments:
              description: Additional environments for a training process
              type: object
            defaultImage:
              description: Default training Docker image
              type: string
            entrypoint:
              description: Path to binary which starts a training process
              type: string
          required:
          - entrypoint
          - defaultImage
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
