apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    {{- include "odahuflow.helm-labels" (dict "component" "operator" "root" .) | nindent 4 }}
    controller-tools.k8s.io: "1.0"
  name: packagingintegrations.odahuflow.odahu.org
spec:
  group: odahuflow.odahu.org
  names:
    kind: PackagingIntegration
    plural: packagingintegrations
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            defaultImage:
              type: string
            entrypoint:
              type: string
            privileged:
              type: boolean
            schema:
              properties:
                arguments:
                  properties:
                    properties:
                      type: string
                    required:
                      items:
                        type: string
                      type: array
                  required:
                  - properties
                  type: object
                targets:
                  items:
                    properties:
                      connectionTypes:
                        items:
                          type: string
                        type: array
                      default:
                        type: string
                      name:
                        type: string
                      required:
                        type: boolean
                    required:
                    - name
                    - connectionTypes
                    - default
                    - required
                    type: object
                  type: array
              required:
              - arguments
              type: object
          required:
          - entrypoint
          - schema
          type: object
        status:
          properties:
            createdAt:
              format: date-time
              type: string
            updatedAt:
              format: date-time
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
